### PR TITLE
[ECI-420] Use Bearer authorization for requests

### LINKED ISSUE #25: Is there a reason the Bearer authorization header is not used?
We have a working Drip integration, but were looking to switch to the official library. But [the way authentication happens](https://github.com/DripEmail/drip-php/blob/b1ddc423ef18495c236e1aad6f9309d2fcbe12dd/src/Client.php#L337-L352) does not work for us (we get authentication errors). However if switch to using the Bearer authorization token header, things work as expected. E.g.

```php
... 
$client = new \GuzzleHttp\Client();

$req_params = [
    'base_uri' => $this->api_end_point,
    'handler' => $stack,
    'timeout' => $this->timeout,
    'connect_timeout' => $this->connect_timeout,
    'http_errors' => false,
    'headers'  => array(
        'User-Agent' => $this->user_agent(),
        'Accept' => 'application/json, text/javascript, */*; q=0.01',
        'Content-Type' => 'application/vnd.api+json',
    	'Authorization' => 'Bearer ' . $this->api_token,
    ),
];
... switch case statement ...

$res = $client->request($req_method, $url, $req_params); 
```

### PR DESCRIPTION
**Pull request by tiannaavery**
Closes #25 

Fulfills request to use Bearer authorization. I successfully tested this locally.

Currently, the way the documentation says an access token can be used is not valid. The new API definition is as follows.
```
$client = new \Drip\Client(["account_id" => "YOUR_ACCOUNT_ID", "access_token" => "YOUR_ACCESS_TOKEN"]);
$client = new \Drip\Client(["account_id" => "YOUR_ACCOUNT_ID", "api_key" => "YOUR_API_KEY"]);
```

The intention is to continue to support the previous client definition and maybe remove it eventually.
```
$client = new \Drip\Client("YOUR_API_KEY", "YOUR_ACCOUNT_ID");
```

I also changed references in the code from "api token" to "api key" just for clarity and consistency.

 Very open for suggestions on how this could be cleaned up or made better.

### CODE REVIEW

**Review by atongen — APPROVED** [review]
:+1:

File: src/Exception/InvalidApiKeyException.php [hunk 1]
```diff
@@ -0,0 +1,7 @@
+<?php
+
+namespace Drip\Exception;
+
+class InvalidApiKeyException extends DripException
```
Comment (will-in-wi) [inline src/Exception/InvalidApiKeyException.php:5]: This is going to sound kind of absurd, but could we also keep `InvalidApiTokenException` and have this new exception class inherit from it? That way, if someone has a `catch` block which is depending on this class name, we aren't breaking compatibility.

File: src/Client.php [hunk 2]
```diff
@@ -36,38 +41,102 @@ class Client
...
+            }
+
+            if (array_key_exists('api_end_point', $params[0])) {
+                $this->api_end_point = $params[0]['api_end_point'];
+            }
+            if (array_key_exists('guzzle_stack_constructor', $params[0])) {
+                $this->guzzle_stack_constructor = $params[0]['guzzle_stack_constructor'];
+            }
+
+            if (empty($account_id) || !preg_match('#^[\w-]+$#si', $account_id)) {
```
Comment (will-in-wi) [inline src/Client.php:77]: Per our earlier conversation about cleaning up some of this duplication, the idea struck me that some protected setters might be nice. For example, adding `protected function set_account_id($account_id)` which also trims and raises if the account ID is empty or invalid might clean up this code.

File: src/Client.php [hunk 3]
```diff
@@ -386,7 +455,7 @@ protected function make_request($url, $params = array(), $req_method = self::GET
         ]);
 
         $req_params = [
-            'auth' => [$this->api_token, ''],
+            'auth' => [$this->api_key, ''],
```
Comment (will-in-wi) [inline src/Client.php:458]: I'd suggest moving this into an `else` block on the `if ($this->bearer_auth)` conditional rather than setting it here and then unsetting it.

File: src/Client.php [hunk 4]
```diff
@@ -397,6 +466,11 @@ protected function make_request($url, $params = array(), $req_method = self::GET
             'http_errors' => false,
         ];
 
+        if ($this->bearer_auth) {
```
Comment (will-in-wi) [inline src/Client.php:469]: Would this all be simpler if we check for `$this->api_key` to not be empty rather than having an additional `bearer_auth` boolean?

**Review by will-in-wi — COMMENTED** [review]
This looks great!
